language: node_js
node_js:
  - "8"
  - "10"
  - "12"
  - "14"
  - node
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
script: "npm run-script travis"
